// SmartCard — Liste d'ingrédients pour l'autocomplétion
// Format: { name, emoji, unit, kcal (pour 100g/100ml), category }
// Utilisé dans : ajout liste de courses, frigo, création recette

const INGREDIENTS_DB = [
  // ── VIANDES ──────────────────────────────────────────────
  {name:'Poulet (blanc)', emoji:'🍗', unit:'g', kcal:110, cat:'viandes'},
  {name:'Poulet (cuisse)', emoji:'🍗', unit:'g', kcal:177, cat:'viandes'},
  {name:'Poulet rôti', emoji:'🍗', unit:'g', kcal:175, cat:'viandes'},
  {name:'Steak haché (15%)', emoji:'🥩', unit:'g', kcal:217, cat:'viandes'},
  {name:'Steak haché (5%)', emoji:'🥩', unit:'g', kcal:120, cat:'viandes'},
  {name:'Boeuf (entrecôte)', emoji:'🥩', unit:'g', kcal:250, cat:'viandes'},
  {name:'Boeuf (filet)', emoji:'🥩', unit:'g', kcal:140, cat:'viandes'},
  {name:'Boeuf bourguignon', emoji:'🥩', unit:'g', kcal:155, cat:'viandes'},
  {name:'Veau (escalope)', emoji:'🥩', unit:'g', kcal:105, cat:'viandes'},
  {name:'Veau (côte)', emoji:'🥩', unit:'g', kcal:185, cat:'viandes'},
  {name:'Porc (côtelette)', emoji:'🥩', unit:'g', kcal:245, cat:'viandes'},
  {name:'Porc (filet)', emoji:'🥩', unit:'g', kcal:120, cat:'viandes'},
  {name:'Jambon blanc', emoji:'🥩', unit:'g', kcal:107, cat:'viandes'},
  {name:'Jambon cru', emoji:'🥩', unit:'g', kcal:265, cat:'viandes'},
  {name:'Lardons', emoji:'🥓', unit:'g', kcal:335, cat:'viandes'},
  {name:'Bacon', emoji:'🥓', unit:'g', kcal:310, cat:'viandes'},
  {name:'Saucisse', emoji:'🌭', unit:'g', kcal:290, cat:'viandes'},
  {name:'Merguez', emoji:'🌭', unit:'g', kcal:305, cat:'viandes'},
  {name:'Dinde (escalope)', emoji:'🦃', unit:'g', kcal:99, cat:'viandes'},
  {name:'Canard (magret)', emoji:'🦆', unit:'g', kcal:201, cat:'viandes'},
  {name:'Agneau (gigot)', emoji:'🥩', unit:'g', kcal:182, cat:'viandes'},
  {name:'Agneau (côtelette)', emoji:'🥩', unit:'g', kcal:254, cat:'viandes'},

  // ── POISSONS & FRUITS DE MER ─────────────────────────────
  {name:'Saumon (filet)', emoji:'🐟', unit:'g', kcal:208, cat:'poissons'},
  {name:'Saumon fumé', emoji:'🐟', unit:'g', kcal:173, cat:'poissons'},
  {name:'Thon (en boîte)', emoji:'🐟', unit:'g', kcal:103, cat:'poissons'},
  {name:'Thon (frais)', emoji:'🐟', unit:'g', kcal:144, cat:'poissons'},
  {name:'Cabillaud', emoji:'🐟', unit:'g', kcal:82, cat:'poissons'},
  {name:'Sole', emoji:'🐟', unit:'g', kcal:83, cat:'poissons'},
  {name:'Daurade', emoji:'🐟', unit:'g', kcal:121, cat:'poissons'},
  {name:'Bar (loup)', emoji:'🐟', unit:'g', kcal:97, cat:'poissons'},
  {name:'Sardines (boîte)', emoji:'🐟', unit:'g', kcal:208, cat:'poissons'},
  {name:'Maquereau', emoji:'🐟', unit:'g', kcal:205, cat:'poissons'},
  {name:'Truite', emoji:'🐟', unit:'g', kcal:119, cat:'poissons'},
  {name:'Crevettes', emoji:'🦐', unit:'g', kcal:85, cat:'poissons'},
  {name:'Moules', emoji:'🦪', unit:'g', kcal:86, cat:'poissons'},
  {name:'Coquilles Saint-Jacques', emoji:'🦪', unit:'g', kcal:88, cat:'poissons'},
  {name:'Calamars', emoji:'🦑', unit:'g', kcal:82, cat:'poissons'},
  {name:'Crevettes décortiquées', emoji:'🦐', unit:'g', kcal:85, cat:'poissons'},

  // ── LÉGUMES ──────────────────────────────────────────────
  {name:'Tomates', emoji:'🍅', unit:'g', kcal:18, cat:'legumes'},
  {name:'Tomates cerises', emoji:'🍅', unit:'g', kcal:20, cat:'legumes'},
  {name:'Tomates pelées (boîte)', emoji:'🍅', unit:'g', kcal:21, cat:'legumes'},
  {name:'Carottes', emoji:'🥕', unit:'g', kcal:41, cat:'legumes'},
  {name:'Courgettes', emoji:'🥒', unit:'g', kcal:17, cat:'legumes'},
  {name:'Aubergine', emoji:'🍆', unit:'g', kcal:25, cat:'legumes'},
  {name:'Poivron rouge', emoji:'🌶️', unit:'g', kcal:31, cat:'legumes'},
  {name:'Poivron vert', emoji:'🫑', unit:'g', kcal:20, cat:'legumes'},
  {name:'Poivron jaune', emoji:'🫑', unit:'g', kcal:27, cat:'legumes'},
  {name:'Oignon', emoji:'🧅', unit:'g', kcal:40, cat:'legumes'},
  {name:'Oignon rouge', emoji:'🧅', unit:'g', kcal:42, cat:'legumes'},
  {name:'Ail', emoji:'🧄', unit:'g', kcal:149, cat:'legumes'},
  {name:'Échalote', emoji:'🧅', unit:'g', kcal:72, cat:'legumes'},
  {name:'Poireau', emoji:'🌿', unit:'g', kcal:31, cat:'legumes'},
  {name:'Brocoli', emoji:'🥦', unit:'g', kcal:34, cat:'legumes'},
  {name:'Chou-fleur', emoji:'🥦', unit:'g', kcal:25, cat:'legumes'},
  {name:'Chou blanc', emoji:'🥬', unit:'g', kcal:25, cat:'legumes'},
  {name:'Épinards', emoji:'🥬', unit:'g', kcal:23, cat:'legumes'},
  {name:'Salade verte', emoji:'🥬', unit:'g', kcal:15, cat:'legumes'},
  {name:'Laitue', emoji:'🥬', unit:'g', kcal:15, cat:'legumes'},
  {name:'Roquette', emoji:'🥬', unit:'g', kcal:25, cat:'legumes'},
  {name:'Mesclun', emoji:'🥬', unit:'g', kcal:20, cat:'legumes'},
  {name:'Champignons de Paris', emoji:'🍄', unit:'g', kcal:22, cat:'legumes'},
  {name:'Champignons shiitake', emoji:'🍄', unit:'g', kcal:36, cat:'legumes'},
  {name:'Concombre', emoji:'🥒', unit:'g', kcal:15, cat:'legumes'},
  {name:'Céleri', emoji:'🌿', unit:'g', kcal:16, cat:'legumes'},
  {name:'Céleri-rave', emoji:'🌿', unit:'g', kcal:42, cat:'legumes'},
  {name:'Fenouil', emoji:'🌿', unit:'g', kcal:31, cat:'legumes'},
  {name:'Asperges', emoji:'🌿', unit:'g', kcal:20, cat:'legumes'},
  {name:'Haricots verts', emoji:'🫘', unit:'g', kcal:31, cat:'legumes'},
  {name:'Petit pois', emoji:'🫛', unit:'g', kcal:81, cat:'legumes'},
  {name:'Maïs (en boîte)', emoji:'🌽', unit:'g', kcal:86, cat:'legumes'},
  {name:'Betterave', emoji:'🫚', unit:'g', kcal:43, cat:'legumes'},
  {name:'Radis', emoji:'🌶️', unit:'g', kcal:16, cat:'legumes'},
  {name:'Navet', emoji:'🌿', unit:'g', kcal:28, cat:'legumes'},
  {name:'Artichaut', emoji:'🌿', unit:'g', kcal:53, cat:'legumes'},
  {name:'Endive', emoji:'🥬', unit:'g', kcal:17, cat:'legumes'},
  {name:'Mâche', emoji:'🥬', unit:'g', kcal:21, cat:'legumes'},
  {name:'Potiron', emoji:'🎃', unit:'g', kcal:26, cat:'legumes'},
  {name:'Butternut (courge)', emoji:'🎃', unit:'g', kcal:45, cat:'legumes'},
  {name:'Patate douce', emoji:'🍠', unit:'g', kcal:86, cat:'legumes'},
  {name:'Pomme de terre', emoji:'🥔', unit:'g', kcal:77, cat:'legumes'},
  {name:'Gingembre', emoji:'🫚', unit:'g', kcal:80, cat:'legumes'},
  {name:'Piment', emoji:'🌶️', unit:'g', kcal:40, cat:'legumes'},

  // ── FRUITS ───────────────────────────────────────────────
  {name:'Pomme', emoji:'🍎', unit:'g', kcal:52, cat:'fruits'},
  {name:'Poire', emoji:'🍐', unit:'g', kcal:57, cat:'fruits'},
  {name:'Banane', emoji:'🍌', unit:'g', kcal:89, cat:'fruits'},
  {name:'Orange', emoji:'🍊', unit:'g', kcal:47, cat:'fruits'},
  {name:'Citron', emoji:'🍋', unit:'g', kcal:29, cat:'fruits'},
  {name:'Citron vert', emoji:'🍋', unit:'g', kcal:30, cat:'fruits'},
  {name:'Fraises', emoji:'🍓', unit:'g', kcal:32, cat:'fruits'},
  {name:'Framboises', emoji:'🍓', unit:'g', kcal:52, cat:'fruits'},
  {name:'Myrtilles', emoji:'🫐', unit:'g', kcal:57, cat:'fruits'},
  {name:'Cerises', emoji:'🍒', unit:'g', kcal:63, cat:'fruits'},
  {name:'Raisin', emoji:'🍇', unit:'g', kcal:69, cat:'fruits'},
  {name:'Pêche', emoji:'🍑', unit:'g', kcal:39, cat:'fruits'},
  {name:'Abricot', emoji:'🍑', unit:'g', kcal:48, cat:'fruits'},
  {name:'Melon', emoji:'🍈', unit:'g', kcal:34, cat:'fruits'},
  {name:'Pastèque', emoji:'🍉', unit:'g', kcal:30, cat:'fruits'},
  {name:'Ananas', emoji:'🍍', unit:'g', kcal:50, cat:'fruits'},
  {name:'Mangue', emoji:'🥭', unit:'g', kcal:60, cat:'fruits'},
  {name:'Avocat', emoji:'🥑', unit:'g', kcal:160, cat:'fruits'},
  {name:'Kiwi', emoji:'🥝', unit:'g', kcal:61, cat:'fruits'},
  {name:'Figue', emoji:'🍑', unit:'g', kcal:74, cat:'fruits'},
  {name:'Prune', emoji:'🍑', unit:'g', kcal:46, cat:'fruits'},
  {name:'Grenade', emoji:'🍎', unit:'g', kcal:83, cat:'fruits'},

  // ── FÉCULENTS ────────────────────────────────────────────
  {name:'Pâtes (sèches)', emoji:'🍝', unit:'g', kcal:352, cat:'fec'},
  {name:'Spaghetti', emoji:'🍝', unit:'g', kcal:352, cat:'fec'},
  {name:'Penne', emoji:'🍝', unit:'g', kcal:352, cat:'fec'},
  {name:'Tagliatelles', emoji:'🍝', unit:'g', kcal:352, cat:'fec'},
  {name:'Riz blanc', emoji:'🍚', unit:'g', kcal:350, cat:'fec'},
  {name:'Riz complet', emoji:'🍚', unit:'g', kcal:337, cat:'fec'},
  {name:'Riz basmati', emoji:'🍚', unit:'g', kcal:346, cat:'fec'},
  {name:'Quinoa', emoji:'🌾', unit:'g', kcal:368, cat:'fec'},
  {name:'Boulgour', emoji:'🌾', unit:'g', kcal:342, cat:'fec'},
  {name:'Semoule', emoji:'🌾', unit:'g', kcal:360, cat:'fec'},
  {name:'Pain de mie', emoji:'🍞', unit:'g', kcal:263, cat:'fec'},
  {name:'Pain complet', emoji:'🍞', unit:'g', kcal:246, cat:'fec'},
  {name:'Baguette', emoji:'🥖', unit:'g', kcal:280, cat:'fec'},
  {name:'Farine de blé T55', emoji:'🌾', unit:'g', kcal:360, cat:'fec'},
  {name:'Farine complète T80', emoji:'🌾', unit:'g', kcal:335, cat:'fec'},
  {name:'Flocons d\'avoine', emoji:'🌾', unit:'g', kcal:370, cat:'fec'},
  {name:'Lentilles vertes', emoji:'🫘', unit:'g', kcal:116, cat:'fec'},
  {name:'Lentilles corail', emoji:'🫘', unit:'g', kcal:355, cat:'fec'},
  {name:'Pois chiches', emoji:'🫘', unit:'g', kcal:364, cat:'fec'},
  {name:'Haricots rouges', emoji:'🫘', unit:'g', kcal:127, cat:'fec'},
  {name:'Haricots blancs', emoji:'🫘', unit:'g', kcal:339, cat:'fec'},
  {name:'Fèves', emoji:'🫘', unit:'g', kcal:341, cat:'fec'},
  {name:'Polenta', emoji:'🌽', unit:'g', kcal:363, cat:'fec'},

  // ── PRODUITS LAITIERS & OEUFS ────────────────────────────
  {name:'Oeufs', emoji:'🥚', unit:'g', kcal:155, cat:'lait'},
  {name:'Lait entier', emoji:'🥛', unit:'ml', kcal:61, cat:'lait'},
  {name:'Lait demi-écrémé', emoji:'🥛', unit:'ml', kcal:46, cat:'lait'},
  {name:'Lait écrémé', emoji:'🥛', unit:'ml', kcal:35, cat:'lait'},
  {name:'Lait végétal (amande)', emoji:'🥛', unit:'ml', kcal:20, cat:'lait'},
  {name:'Lait de coco', emoji:'🥛', unit:'ml', kcal:197, cat:'lait'},
  {name:'Yaourt nature', emoji:'🍦', unit:'g', kcal:59, cat:'lait'},
  {name:'Yaourt grec', emoji:'🍦', unit:'g', kcal:97, cat:'lait'},
  {name:'Fromage blanc', emoji:'🍦', unit:'g', kcal:53, cat:'lait'},
  {name:'Crème fraîche', emoji:'🍦', unit:'g', kcal:292, cat:'lait'},
  {name:'Crème liquide', emoji:'🍦', unit:'ml', kcal:335, cat:'lait'},
  {name:'Beurre', emoji:'🧈', unit:'g', kcal:717, cat:'lait'},
  {name:'Emmental (râpé)', emoji:'🧀', unit:'g', kcal:380, cat:'lait'},
  {name:'Comté', emoji:'🧀', unit:'g', kcal:413, cat:'lait'},
  {name:'Gruyère', emoji:'🧀', unit:'g', kcal:396, cat:'lait'},
  {name:'Mozzarella', emoji:'🧀', unit:'g', kcal:280, cat:'lait'},
  {name:'Parmesan', emoji:'🧀', unit:'g', kcal:431, cat:'lait'},
  {name:'Feta', emoji:'🧀', unit:'g', kcal:264, cat:'lait'},
  {name:'Chèvre frais', emoji:'🧀', unit:'g', kcal:230, cat:'lait'},
  {name:'Camembert', emoji:'🧀', unit:'g', kcal:300, cat:'lait'},
  {name:'Ricotta', emoji:'🧀', unit:'g', kcal:174, cat:'lait'},
  {name:'Crème de fromage', emoji:'🧀', unit:'g', kcal:210, cat:'lait'},
  {name:'Lait concentré sucré', emoji:'🥛', unit:'g', kcal:328, cat:'lait'},

  // ── MATIÈRES GRASSES ─────────────────────────────────────
  {name:'Huile d\'olive', emoji:'🫒', unit:'ml', kcal:884, cat:'matieres'},
  {name:'Huile de tournesol', emoji:'🌻', unit:'ml', kcal:884, cat:'matieres'},
  {name:'Huile de coco', emoji:'🥥', unit:'ml', kcal:862, cat:'matieres'},
  {name:'Huile de sésame', emoji:'🫒', unit:'ml', kcal:884, cat:'matieres'},
  {name:'Huile de colza', emoji:'🫒', unit:'ml', kcal:884, cat:'matieres'},
  {name:'Beurre de cacahuète', emoji:'🥜', unit:'g', kcal:598, cat:'matieres'},
  {name:'Purée d\'amande', emoji:'🥜', unit:'g', kcal:614, cat:'matieres'},
  {name:'Tahini', emoji:'🫒', unit:'g', kcal:595, cat:'matieres'},

  // ── CONDIMENTS & SAUCES ──────────────────────────────────
  {name:'Moutarde', emoji:'🫙', unit:'g', kcal:67, cat:'condiments'},
  {name:'Ketchup', emoji:'🍅', unit:'g', kcal:101, cat:'condiments'},
  {name:'Mayonnaise', emoji:'🫙', unit:'g', kcal:680, cat:'condiments'},
  {name:'Vinaigre balsamique', emoji:'🫙', unit:'ml', kcal:88, cat:'condiments'},
  {name:'Vinaigre de cidre', emoji:'🫙', unit:'ml', kcal:21, cat:'condiments'},
  {name:'Sauce soja', emoji:'🫙', unit:'ml', kcal:60, cat:'condiments'},
  {name:'Sauce tomate', emoji:'🍅', unit:'g', kcal:44, cat:'condiments'},
  {name:'Concentré de tomates', emoji:'🍅', unit:'g', kcal:82, cat:'condiments'},
  {name:'Sauce pesto', emoji:'🌿', unit:'g', kcal:450, cat:'condiments'},
  {name:'Bouillon de légumes', emoji:'🫙', unit:'ml', kcal:10, cat:'condiments'},
  {name:'Bouillon de poulet', emoji:'🫙', unit:'ml', kcal:15, cat:'condiments'},
  {name:'Crème de coco', emoji:'🥥', unit:'ml', kcal:330, cat:'condiments'},
  {name:'Sauce Worcestershire', emoji:'🫙', unit:'ml', kcal:78, cat:'condiments'},
  {name:'Sauce Tabasco', emoji:'🌶️', unit:'ml', kcal:12, cat:'condiments'},

  // ── ÉPICES & HERBES ───────────────────────────────────────
  {name:'Sel', emoji:'🧂', unit:'g', kcal:0, cat:'epices'},
  {name:'Poivre', emoji:'🧂', unit:'g', kcal:255, cat:'epices'},
  {name:'Curcuma', emoji:'🟡', unit:'g', kcal:354, cat:'epices'},
  {name:'Cumin', emoji:'🟡', unit:'g', kcal:375, cat:'epices'},
  {name:'Paprika', emoji:'🔴', unit:'g', kcal:282, cat:'epices'},
  {name:'Curry en poudre', emoji:'🟡', unit:'g', kcal:325, cat:'epices'},
  {name:'Coriandre (poudre)', emoji:'🟡', unit:'g', kcal:298, cat:'epices'},
  {name:'Cannelle', emoji:'🟤', unit:'g', kcal:247, cat:'epices'},
  {name:'Ras-el-hanout', emoji:'🟡', unit:'g', kcal:325, cat:'epices'},
  {name:'Herbes de Provence', emoji:'🌿', unit:'g', kcal:259, cat:'epices'},
  {name:'Thym', emoji:'🌿', unit:'g', kcal:101, cat:'epices'},
  {name:'Romarin', emoji:'🌿', unit:'g', kcal:131, cat:'epices'},
  {name:'Basilic frais', emoji:'🌿', unit:'g', kcal:22, cat:'epices'},
  {name:'Persil frais', emoji:'🌿', unit:'g', kcal:36, cat:'epices'},
  {name:'Ciboulette', emoji:'🌿', unit:'g', kcal:30, cat:'epices'},
  {name:'Coriandre fraîche', emoji:'🌿', unit:'g', kcal:23, cat:'epices'},
  {name:'Menthe fraîche', emoji:'🌿', unit:'g', kcal:44, cat:'epices'},
  {name:'Laurier', emoji:'🌿', unit:'g', kcal:313, cat:'epices'},
  {name:'Noix de muscade', emoji:'🟤', unit:'g', kcal:525, cat:'epices'},
  {name:'Gingembre (poudre)', emoji:'🟡', unit:'g', kcal:335, cat:'epices'},
  {name:'Piment d\'Espelette', emoji:'🌶️', unit:'g', kcal:282, cat:'epices'},
  {name:'Levure chimique', emoji:'🧂', unit:'g', kcal:97, cat:'epices'},
  {name:'Bicarbonate', emoji:'🧂', unit:'g', kcal:0, cat:'epices'},

  // ── SUCRÉ & BOULANGERIE ───────────────────────────────────
  {name:'Sucre blanc', emoji:'🍬', unit:'g', kcal:387, cat:'sucre'},
  {name:'Sucre roux', emoji:'🍬', unit:'g', kcal:377, cat:'sucre'},
  {name:'Miel', emoji:'🍯', unit:'g', kcal:304, cat:'sucre'},
  {name:'Sirop d\'érable', emoji:'🍯', unit:'ml', kcal:260, cat:'sucre'},
  {name:'Chocolat noir 70%', emoji:'🍫', unit:'g', kcal:598, cat:'sucre'},
  {name:'Chocolat au lait', emoji:'🍫', unit:'g', kcal:535, cat:'sucre'},
  {name:'Chocolat blanc', emoji:'🍫', unit:'g', kcal:539, cat:'sucre'},
  {name:'Cacao en poudre', emoji:'🍫', unit:'g', kcal:228, cat:'sucre'},
  {name:'Confiture', emoji:'🫙', unit:'g', kcal:250, cat:'sucre'},
  {name:'Pâte à tartiner', emoji:'🫙', unit:'g', kcal:546, cat:'sucre'},
  {name:'Vanille (extrait)', emoji:'🟤', unit:'ml', kcal:288, cat:'sucre'},
  {name:'Sucre glace', emoji:'🍬', unit:'g', kcal:394, cat:'sucre'},
  {name:'Poudre d\'amande', emoji:'🥜', unit:'g', kcal:578, cat:'sucre'},
  {name:'Pâte feuilletée', emoji:'🥐', unit:'g', kcal:400, cat:'sucre'},
  {name:'Pâte brisée', emoji:'🥐', unit:'g', kcal:400, cat:'sucre'},

  // ── BOISSONS ─────────────────────────────────────────────
  {name:'Eau', emoji:'💧', unit:'ml', kcal:0, cat:'boissons'},
  {name:'Jus d\'orange', emoji:'🧃', unit:'ml', kcal:45, cat:'boissons'},
  {name:'Jus de pomme', emoji:'🧃', unit:'ml', kcal:46, cat:'boissons'},
  {name:'Café', emoji:'☕', unit:'ml', kcal:2, cat:'boissons'},
  {name:'Thé', emoji:'🍵', unit:'ml', kcal:2, cat:'boissons'},
  {name:'Vin rouge', emoji:'🍷', unit:'ml', kcal:85, cat:'boissons'},
  {name:'Vin blanc', emoji:'🥂', unit:'ml', kcal:77, cat:'boissons'},

  // ── CONSERVES & ÉPICERIE ──────────────────────────────────
  {name:'Pulpe de tomates', emoji:'🍅', unit:'g', kcal:26, cat:'conserves'},
  {name:'Tomates entières (boîte)', emoji:'🍅', unit:'g', kcal:20, cat:'conserves'},
  {name:'Pois chiches (boîte)', emoji:'🫘', unit:'g', kcal:139, cat:'conserves'},
  {name:'Lentilles (boîte)', emoji:'🫘', unit:'g', kcal:116, cat:'conserves'},
  {name:'Haricots rouges (boîte)', emoji:'🫘', unit:'g', kcal:127, cat:'conserves'},
  {name:'Maïs (boîte)', emoji:'🌽', unit:'g', kcal:86, cat:'conserves'},
  {name:'Olives noires', emoji:'🫒', unit:'g', kcal:145, cat:'conserves'},
  {name:'Olives vertes', emoji:'🫒', unit:'g', kcal:115, cat:'conserves'},
  {name:'Câpres', emoji:'🫒', unit:'g', kcal:23, cat:'conserves'},
  {name:'Anchois (boîte)', emoji:'🐟', unit:'g', kcal:210, cat:'conserves'},
  {name:'Thon (boîte à l\'huile)', emoji:'🐟', unit:'g', kcal:200, cat:'conserves'},
  {name:'Thon (boîte au naturel)', emoji:'🐟', unit:'g', kcal:103, cat:'conserves'},

  // ── FRUITS SECS & OLÉAGINEUX ─────────────────────────────
  {name:'Amandes', emoji:'🥜', unit:'g', kcal:578, cat:'olagineux'},
  {name:'Noix', emoji:'🥜', unit:'g', kcal:654, cat:'olagineux'},
  {name:'Noix de cajou', emoji:'🥜', unit:'g', kcal:553, cat:'olagineux'},
  {name:'Noisettes', emoji:'🥜', unit:'g', kcal:628, cat:'olagineux'},
  {name:'Pistaches', emoji:'🥜', unit:'g', kcal:562, cat:'olagineux'},
  {name:'Graines de sésame', emoji:'🌾', unit:'g', kcal:573, cat:'olagineux'},
  {name:'Graines de tournesol', emoji:'🌻', unit:'g', kcal:584, cat:'olagineux'},
  {name:'Graines de chia', emoji:'🌾', unit:'g', kcal:486, cat:'olagineux'},
  {name:'Noix de coco râpée', emoji:'🥥', unit:'g', kcal:354, cat:'olagineux'},
  {name:'Raisins secs', emoji:'🍇', unit:'g', kcal:299, cat:'olagineux'},
  {name:'Dattes', emoji:'🍑', unit:'g', kcal:282, cat:'olagineux'},
  {name:'Pruneaux', emoji:'🍑', unit:'g', kcal:240, cat:'olagineux'},
  {name:'Abricots secs', emoji:'🍑', unit:'g', kcal:241, cat:'olagineux'},
];

// Catégories labels
const INGREDIENTS_CATEGORIES = {
  viandes:   { label:'🥩 Viandes',                   color:'#e74c3c' },
  poissons:  { label:'🐟 Poissons & fruits de mer',  color:'#3498db' },
  legumes:   { label:'🥦 Légumes',                   color:'#27ae60' },
  fruits:    { label:'🍎 Fruits',                    color:'#e67e22' },
  fec:       { label:'🍝 Féculents & légumineuses',  color:'#f39c12' },
  lait:      { label:'🥛 Produits laitiers & œufs',  color:'#9b59b6' },
  matieres:  { label:'🫒 Matières grasses',           color:'#f1c40f' },
  condiments:{ label:'🫙 Condiments & sauces',       color:'#e67e22' },
  epices:    { label:'🌿 Épices & herbes',            color:'#1abc9c' },
  sucre:     { label:'🍫 Sucré & boulangerie',       color:'#c0392b' },
  boissons:  { label:'☕ Boissons',                   color:'#2980b9' },
  conserves: { label:'🥫 Conserves & épicerie',      color:'#7f8c8d' },
  olagineux: { label:'🥜 Fruits secs & oléagineux',  color:'#d35400' },
};

// Search function
function searchIngredients(query, limit) {
  if(!query || query.length < 1) return [];
  limit = limit || 12;
  const q = query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  return INGREDIENTS_DB
    .filter(i => {
      const n = i.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
      return n.includes(q);
    })
    .sort((a,b) => {
      const na = a.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
      const nb = b.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
      // Starts-with first
      const aStarts = na.startsWith(q) ? 0 : 1;
      const bStarts = nb.startsWith(q) ? 0 : 1;
      return aStarts - bStarts || na.localeCompare(nb);
    })
    .slice(0, limit);
}

// Export for use in main app
if(typeof module !== 'undefined') module.exports = { INGREDIENTS_DB, INGREDIENTS_CATEGORIES, searchIngredients };
